---
name: ElectronJS Builder

on:
  pull_request:
    branches: [inElectronJs]

jobs:
  build:
    name: Build and Package ElectronJS
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.12
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'

      - name: Run lint
        run: npm run lint

      - name: Build production
        run: npm run build.prod

      - name: Package ElectronJS app
        run: npm run package

      - name: Make ElectronJS distributables
        run: npm run make
